### ISSUE TITLE
アーカイブボタン

### ISSUE THREAD

**Issue by pandeiro245** [mashupwork/kintone_portal#22]
# 仕様
* [x] 一覧ページにアーカイブボタンを設置
* [x] アーカイブボタンを押すと該当項目が該当ページに保存される（ハードコーディング）
* [x] アーカイブボタンを押すと該当項目が該当ページに保存される（汎用化）
* [x] 編集中に２回アーカイブボタンを押しても２回アーカイブ化されるようにする
* [x] レコード詳細ページ（detail.show）においてarchive_doというチェックボックスがない場合、勝手に追加する
* [ ] 一覧（index.show)にarchive_doというチェックボックスがない場合、勝手に追加する refs #30
* [ ] レコード一覧ページだけでなくレコード詳細ページでも同様に機能させる

**Comment by yosimurat** [comment]
まずは環境構築から行いたいと思います。
coffee scriptをコンパイルして、index.jsとarchive.jsを作成してみましたが、これを何処に登録するか具体的なアプリ名などを教えていただいてもいいでしょうか？

また、jqueryなど必要なライブラリがあれば教えていただけますか？
環境構築がうまくいったかを判断するため、アーカイブボタンがどの画面のどの位置に表示されるかも確認させてください。

以上、よろしくお願い致します。

**Comment by pandeiro245** [comment]
@yosimurat ご確認ありがとうございます。取り急ぎ下記に記載させて頂きました。
引き続き不明点ありましたらお気軽にお知らせ頂ければと思います。
https://ruffnote.com/pandeiro245/kintone_portal

**Comment by yosimurat** [comment]
ラフノートに登録・ログインして確認してみましたが、
リンク先が404エラーとなっております。

とりあえず、適当なKintoneアプリ（案件管理アプリ）などに登録して試してみます。

**Comment by pandeiro245** [comment]
@yosimurat 非公開になっていたので公開しました！

**Comment by yosimurat** [comment]
@pandeiro245  環境構築のノートを確認しました。ありがとうございます。
手順に従って、Kintoneで環境構築を進めているのですが、もしかして下記の設定項目も必要でしょうか？
window.settings.archive_textarea
window.settings.archive_table

任意のアプリ設定の上、確認したのですが、一覧でアーカイブするのチェックを入れた段階で、JavaScriptのエラーで落ちている状態です。
以上、何卒よろしくお願い致します。

**Comment by pandeiro245** [comment]
@yosimurat 大変申し訳ございません！
おっしゃるとおりです、下記マニュアル修正致しました。
https://ruffnote.com/pandeiro245/kintone_portal

こちらで伝わりますでしょうか？

また、次回エラーになった際はエラー内容を共有して頂けると幸いです

**Comment by yosimurat** [comment]
一応動作するようになりました。
![2016-03-22 21 28 58](https://cloud.githubusercontent.com/assets/1275365/13951655/d1fe3a52-f075-11e5-8058-6bd09e5255f1.png)
![2016-03-22 21 39 10](https://cloud.githubusercontent.com/assets/1275365/13951846/90033fac-f076-11e5-805f-0e0521d32ff9.png)


 アーカイブボタンがチェックボックスになっているのは少し気になります。
また、 チェックをつけると、複数行テキストはクリアされるのは仕様でしょうか？

問題なければ、環境構築は完了したものとして、作業を進めます。

**Comment by pandeiro245** [comment]
@yosimurat はい、その仕様で正しいです。
明日、3/23（水）の15時から先方とMTGなので
今日あがるときにできている分でPR頂けると幸いです。
（もちろんその状態でもマージされればクラウドワークスで納品扱いします）

**Comment by yosimurat** [comment]
@pandeiro245 
> 編集中に２回アーカイブボタンを押しても２回アーカイブ化されるようにする

このタスクは完了済みでしょうか？
現状で１回、アーカイブするにチェックをつけたところで、複数行はクリアされますが、
もう一回、複数行に入力してチェックをつけたタイミングで、アーカイブは２件追加され、保存ボタンで確定される動作を確認しました。

完了済みであれば、下記タスクからすすめます。

> フォームにarchive_doというチェックボックスがない場合、勝手に追加する
>  一覧にarchive_doというチェックボックスがない場合、勝手に追加する

**Comment by pandeiro245** [comment]
@yosimurat はい、前者まだ確認できていませんが後者の着手お願いします！

**Comment by yosimurat** [comment]
チェックボックス追加の為のAPIはこのあたりでしょうか。

[https://cybozudev.zendesk.com/hc/ja/articles/204529724-%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%AE%E5%A4%89%E6%9B%B4#anchor_changeform_addfields](url)

調べてみる必要がありますが、明日から予定が詰まっているため、作業は週末ぐらいまで着手できないかもしれません。
申し訳ありませんが、急ぎであれば他のかたにアサインして頂けないでしょうか？

**Comment by pandeiro245** [comment]
@yosimurat はいそうです。このあたりも細かくissue化とassignしていきますね。
